config/routes.rb
Inventory::Application.routes.draw do

  resources :logins

  match 'events/filter/:filter' => 'events#filter'

  resources :wishlists

  match 'wishlists/new/:client_id' => 'wishlists#new_with_client'

  match 'events/day/:date' => 'events#day'

  match 'clients/pickup_lists/:id' => 'clients#pickup_lists'

  match 'picked_up/:pickup_list_id/:product_id' => 'picked_up#pickup'

  resources :wish_list_items

  match 'pickup_lists/new/:client_id' => 'pickup_lists#new_with_client'

  match 'events/new_with_client/:client_id' => 'events#new_with_client'
  
  resources :categories  

  resources :clients 
  
  resources :pickup_lists
  
  resources :levels
  
  devise_for :users
  resources :user, :controller => "user"

  get "roles/new"

  get "roles/create"

  get "roles/index"

  get "roles/edit"

  get "roles/_form"

  devise_for :agents

  resources :donors

  resources :products

  resources :events

  get "user/index"

  get "home/index"

	root :to => "home#index"
	

end

app/models/donor.rb
class Donor < ActiveRecord::Base
  attr_accessible :name, :address, :phone, :email, :product_name, :product_id, :donor_id
  has_many :products
  accepts_nested_attributes_for :products
  paginates_per 10

end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
    before_filter :authenticate_user!    
      load_and_authorize_resource
    
  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.page(params[:page]).order(:name)
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donors }
    end
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
    @donor = Donor.find(params[:id])
    @products = Product.where( :donor_id => @donor )
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/new
  # GET /donors/new.json
  def new
    @donor = Donor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/1/edit
  def edit
    @donor = Donor.find(params[:id])
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(params[:donor])

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render json: @donor, status: :created, location: @donor }
      else
        format.html { render action: "new" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donors/1
  # PUT /donors/1.json
  def update
    @donor = Donor.find(params[:id])

    respond_to do |format|
      if @donor.update_attributes(params[:donor])
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor = Donor.find(params[:id])
    @donor.destroy

    respond_to do |format|
      format.html { redirect_to donors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_form.html.erb
<%= form_for(@donor) do |f| %>
  <% if @donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% @donor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donors/edit.html.erb
<h1>Editing donor</h1>

<%= render 'form' %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', donors_path %>

app/views/donors/index.html.erb
<h2>Listing Donors</h2>

<p class="clearfix">
<% if can? :create, @donors %><%= link_to 'New Donor', new_donor_path, :class => 'btn btn-success' %><% end %>
</p>
<table class="table table-bordered table-condensed table-striped table-hover">
<thead>
<tr>
<th>Name</th>
<th>Address</th>
<th>Phone</th>
<th>Email</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<% @donors.each do |donor| %>
<tr>
    <td><%= link_to "#{donor.name}", donor %></td>
    <td><%= donor.address %></td>
    <td><%= number_to_phone(donor.phone, :area_code => true) %></td>
    <td><%= link_to 'Email', 'mailto: ' + donor.email %></td>
    <td><%= link_to 'Show', donor, :class => 'btn btn-info btn-block' %></td>
    
    <td><% if can? :update, @donors %> 
    <%= link_to 'Edit', edit_donor_path(donor), :class => 'btn btn-warning btn-block' %>
    <% end %></td>
    
    <td><% if can? :destroy, @donors %> 
    <%= link_to 'Destroy', donor, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-block' %>
    <% end %></td>
</tr>
<%= paginate @donors %>
<% end %>
</tbody>
</table>

app/views/donors/new.html.erb
<h1>New donor</h1>

<%= render 'form' %>

<%= link_to 'Back', donors_path %>

app/views/donors/show.html.erb
<p id="notice"><%= notice %></p>

<p class="info"><strong>Name:</strong> <%= @donor.name %></p>
<p class="info"><strong>Address:</strong> <%= @donor.address %></p>
<p class="info"><strong>Phone:</strong> <%= number_to_phone(@donor.phone, :area_code => true, :delimiter => "-") %></p>
<p class="info"><strong>Email:</strong> <%= mail_to @donor.email, "Email", :encode => "hex" %></p>
<p class="info"><strong>Donated Products:</strong></p>
<ul>
	<% if @products %>
		<% @products.collect do |a| %>
		 <li><a href="/products/<%= a.id %>"><%= a.name %></a></li>
		<% end %>
	<% end %>
</ul>
<% if can? :update, @donors %><%= link_to 'Edit', edit_donor_path(@donor), :class => "btn btn-warning" %>
<% end %><%= link_to 'Back', donors_path, :class => "btn btn-inverse"  %>