config/routes.rb
Inventory::Application.routes.draw do

  resources :logins

  match 'events/filter/:filter' => 'events#filter'

  resources :wishlists

  match 'wishlists/new/:client_id' => 'wishlists#new_with_client'

  match 'events/day/:date' => 'events#day'

  match 'clients/pickup_lists/:id' => 'clients#pickup_lists'

  match 'picked_up/:pickup_list_id/:product_id' => 'picked_up#pickup'

  resources :wish_list_items

  match 'pickup_lists/new/:client_id' => 'pickup_lists#new_with_client'

  match 'events/new_with_client/:client_id' => 'events#new_with_client'
  
  resources :categories  

  resources :clients 
  
  resources :pickup_lists
  
  resources :levels
  
  devise_for :users
  resources :user, :controller => "user"

  get "roles/new"

  get "roles/create"

  get "roles/index"

  get "roles/edit"

  get "roles/_form"

  devise_for :agents

  resources :donors

  resources :products

  resources :events

  get "user/index"

  get "home/index"

	root :to => "home#index"
	

end

app/models/wish_list_item.rb
class WishListItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :wishlist
end

app/controllers/wish_list_items_controller.rb
class WishListItemsController < ApplicationController
  # GET /wish_list_items
  # GET /wish_list_items.json
  def index
    @wish_list_items = WishListItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wish_list_items }
    end
  end

  # GET /wish_list_items/1
  # GET /wish_list_items/1.json
  def show
    @wish_list_item = WishListItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wish_list_item }
    end
  end

  # GET /wish_list_items/new
  # GET /wish_list_items/new.json
  def new
    @wish_list_item = WishListItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wish_list_item }
    end
  end

  # GET /wish_list_items/1/edit
  def edit
    @wish_list_item = WishListItem.find(params[:id])
  end

  # POST /wish_list_items
  # POST /wish_list_items.json
  def create
    @wish_list_item = WishListItem.new(params[:wish_list_item])

    respond_to do |format|
      if @wish_list_item.save
        format.html { redirect_to @wish_list_item, notice: 'Wish list item was successfully created.' }
        format.json { render json: @wish_list_item, status: :created, location: @wish_list_item }
      else
        format.html { render action: "new" }
        format.json { render json: @wish_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wish_list_items/1
  # PUT /wish_list_items/1.json
  def update
    @wish_list_item = WishListItem.find(params[:id])

    respond_to do |format|
      if @wish_list_item.update_attributes(params[:wish_list_item])
        format.html { redirect_to @wish_list_item, notice: 'Wish list item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wish_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wish_list_items/1
  # DELETE /wish_list_items/1.json
  def destroy
    @wish_list_item = WishListItem.find(params[:id])
    @wish_list_item.destroy

    respond_to do |format|
      format.html { redirect_to wish_list_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/wish_list_items_helper.rb
module WishListItemsHelper
end

app/views/wish_list_items/_form.html.erb
<%= form_for(@wish_list_item) do |f| %>
  <% if @wish_list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wish_list_item.errors.count, "error") %> prohibited this wish_list_item from being saved:</h2>

      <ul>
      <% @wish_list_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :timestamps %><br />
    <%= f.text_field :timestamps %>
  </div>
  <div class="field">
    <%= f.label :available %><br />
    <%= f.check_box :available %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wish_list_items/edit.html.erb
<h1>Editing wish_list_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @wish_list_item %> |
<%= link_to 'Back', wish_list_items_path %>

app/views/wish_list_items/index.html.erb
<h1>Listing wish_list_items</h1>

<table>
  <tr>
    <th>Category</th>
    <th>Product</th>
    <th>Available</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wish_list_items.each do |wish_list_item| %>
  <tr>
    <td><%= wish_list_item.category_id %></td>
    <td><%= wish_list_item.product_id %></td>
    <td><%= wish_list_item.available %></td>
    <td><%= link_to 'Show', wish_list_item %></td>
    <td><%= link_to 'Edit', edit_wish_list_item_path(wish_list_item) %></td>
    <td><%= link_to 'Destroy', wish_list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wish list item', new_wish_list_item_path %>

app/views/wish_list_items/new.html.erb
<h1>New wish_list_item</h1>

<%= render 'form' %>

<%= link_to 'Back', wish_list_items_path %>

app/views/wish_list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @wish_list_item.category_id %>
</p>

<p>
  <b>Product:</b>
  <%= @wish_list_item.product_id %>
</p>

<p>
  <b>Available:</b>
  <%= @wish_list_item.available %>
</p>


<%= link_to 'Edit', edit_wish_list_item_path(@wish_list_item) %> |
<%= link_to 'Back', wish_list_items_path %>