config/routes.rb
Inventory::Application.routes.draw do

  resources :logins

  match 'events/filter/:filter' => 'events#filter'

  resources :wishlists

  match 'wishlists/new/:client_id' => 'wishlists#new_with_client'

  match 'events/day/:date' => 'events#day'

  match 'clients/pickup_lists/:id' => 'clients#pickup_lists'

  match 'picked_up/:pickup_list_id/:product_id' => 'picked_up#pickup'

  resources :wish_list_items

  match 'pickup_lists/new/:client_id' => 'pickup_lists#new_with_client'

  match 'events/new_with_client/:client_id' => 'events#new_with_client'
  
  resources :categories  

  resources :clients 
  
  resources :pickup_lists
  
  resources :levels
  
  devise_for :users
  resources :user, :controller => "user"

  get "roles/new"

  get "roles/create"

  get "roles/index"

  get "roles/edit"

  get "roles/_form"

  devise_for :agents

  resources :donors

  resources :products

  resources :events

  get "user/index"

  get "home/index"

	root :to => "home#index"
	

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :location, :price, :inventory, :donor, :delivery, :pickup, :accepted, :declined, :reason, :product_id, :product_name, :donor_id, :event_id, :category_id, :pickup_list_id, :wishlist, :quality
  belongs_to :donor
  belongs_to :event
  accepts_nested_attributes_for :donor
  accepts_nested_attributes_for :event
  has_many :pickup_list_products
  has_many :pickup_lists, :through => :pickup_list_products
  belongs_to :category
  accepts_nested_attributes_for :category
  has_many :wish_list_items
  has_many :wishlists, :through => :wish_list_items
  paginates_per 10
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
    load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
	@products = Product.where(:inventory => true).order(:category_id).page(params[:page])
    @donors = Donor.all
    @categories = Category.all
    @products2 = Product.where(:inventory => false).order(:category_id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @donor = Donor.all
    @event = Event.all
    @category = Category.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @category = Category.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @category = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    @category = @product.category
    
    if @product.category.wishlist?
    	@product.status = "0"
    	@product.status_date = Time.now
    	
    	#we are a wish list item... check to see if anybody is looking for us.
    	#maybe we ignore this step here and leave it to daily processing.
    end

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    @category = Category.all

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    @category = Category.all

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
	def complete
	  Pickup_lists.update_all(["inventory=?", false], :id => params[:product_ids])
	  redirect_to clients_path
	end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  
  <hr/>
  
  <div class="field">
  	<%= f.label :category %><br />
  	<%= f.collection_select(:category_id, Category.all, :id, :name, {:include_blank => 'Please select a Category'}) %>
  </div>

  <div class="field">
    <%= f.label "Item Quality" %><br />
    <%= select(:product, :quality, [['Quality A', 'a'], ['Quality B', 'b'], ['Quality C', 'c']]) %>
  </div>
  
  <div class="field">
    <%= f.label :donor %><br />
    <%= f.collection_select(:donor_id, Donor.all, :id, :name, {:include_blank => 'Please select a Donor'}) %>
  </div>
  
  <hr/>

  <div class="field">
    <%= f.label "Is this item Inventoried?" %><br />
	<%= f.label "Yes" %><%= f.radio_button :inventory, true %><br />
	<%= f.label "No" %><%= f.radio_button :inventory, false %>
  </div>
    

  <div class="field accepted">
    <%= f.label :accepted %><br />
	<%= f.label "Yes" %><%= f.radio_button :accepted, true %><br />
	<%= f.label "No" %><%= f.radio_button :accepted, false %>
  </div>

  <div class="field reason">
    <%= f.label "Reason (if declined)" %><br />
    <%= f.text_area :reason %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing <%= @product.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h3>Inventory</h3>
	    <% if can? :create, @products %> 
			<%= link_to 'Add Product To Inventory', new_product_path, :class => 'btn btn-success' %>
		<% end %>	
<section>
<br/>
<table class="table table-bordered table-condensed table-striped table-hover">
<thead>
<tr>
<th>Name</th>
<th>Quality/Value</th>
<th>Location</th>
<th>Notes</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<% @products.each do |product|%>
<tr>
<td><%= link_to "(#{product.category.name}) #{product.name}", product %></td>
<%
	if product.quality == "a"
		val = product.category.price_a
	elsif product.quality == "b"
		val = product.category.price_b
	elsif product.quality == "c"
		val = product.category.price_c
	end
%>
<td><%= product.quality.capitalize %> - <%= number_to_currency(val) %></td>
<td><%= product.location %></td>
<td></td>
<td><%= link_to 'Show', product, :class => 'btn btn-info btn-block' %></td>
<td><% if can? :update, @products %> 
		    <%= link_to 'Edit', edit_product_path(product), :class => 'btn btn-warning btn-block' %>
	    <% end %></td>
<td><% if can? :destroy, @products %> 
		    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-block' %>
		<% end %></td>
</tr>
<%= paginate @products %>
<% end %>
</tbody>
</table>
</section>
<section>
<h4>Non-Inventoried Items</h4>
<table class="table table-bordered table-condensed table-striped table-hover">
<thead>
<tr>
<th>Name</th>
<th>Inventoried?</th>
<th>Accepted?</th>
<th>Reason</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<% @products2.each do |product2|%>
<tr>
<td>(<%= product2.category.name %>) <%= product2.name %></td>
<td><% if product2.inventory == false %>No<% else %>Yes<% end %></td>
<td><% if product2.accepted == false %>No<% else %>Yes<% end %></td>
<td><% if product2.accepted == false %><%= truncate(product2.reason, :length => 30 ) %><% end %></td>
<td><%= link_to 'Show', product2, :class => 'btn btn-info btn-block' %></td>
<td><% if can? :update, @products %> 
		    <%= link_to 'Edit', edit_product_path(product2), :class => 'btn btn-warning btn-block' %>
	    <% end %></td>
<td><% if can? :destroy, @products %> 
		    <%= link_to 'Destroy', product2, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-block' %>
		<% end %></td>
</tr>
<% end %>
</tbody>
</table>
</section>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

  <article class="productlist">
  <div class="column1">
    <strong>Name</strong>
    <p><%= @product.name %></p>
    <% if @product.location != "" %>
    <strong>Location</strong>
    <p><%= @product.location %></p>
    <% end %>
    <strong>Quality</strong>
    <p>Quality <%= @product.quality.capitalize %></p>
    <strong>Inventoried?</strong>
    <p><% if @product.inventory == false %>No<% else %>Yes<% end %></p>
	<% if @product.donor_id? %>
    <strong>Donor</strong>
	<p><%= @product.donor.name %></p>
	<% end %>
	<% if @product.category_id != "" %>
	<strong>Category</strong>
	<p><%= @product.category.name %></p>
	<% end %>
  </div>
  <div class="column2">
<!--    <strong>Delivered?</strong>
    <p><%# if @product.delivery == false %>No<%# else %>Yes<%# end %></p>
    <strong>Picked Up?</strong>
    <p><%# if @product.pickup == false %>No<%# else %>Yes<%# end %></p> -->
    <strong>Accepted?</strong>
    <p><% if @product.accepted == false %>No<% else %>Yes<% end %></p>
    <% if @product.accepted == false %>
    <strong>Reason</strong>
    <p><%= @product.reason %></p>
    <% end %>
  </div>
    <%= link_to 'Back', products_path, :class => "btn btn-inverse" %><% if can? :update, @products %> 
    <%= link_to 'Edit', edit_product_path(@product), :class => "btn btn-warning" %><% end %><% if can? :destroy, @products %> 
    <%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %><% end %><% if can? :create, @events %> <br/><br/>
    <%= link_to "Create Event", new_event_path, :class => "btn btn-success" %><% end %>
  </article>